version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./hello-world:/app
  npm:
    build:
      context: .
      dockerfile: ./npm.dockerfile
    volumes:
      - ./hello-world:/app

